all:
	g++ _serv.cpp ../Client.cpp ../ChatterBox.cpp ../GamePrimitives.cpp -lsfml-network -lsfml-system -o serv
	g++  _cli.cpp ../Client.cpp ../ChatterBox.cpp ../GamePrimitives.cpp -lsfml-network -lsfml-system -o  cli
	
